services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER:-developer}
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - .:/home/host_dir
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
